# Generated by Django 6.0 on 2026-01-03 18:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('allowed_channels', models.JSONField(default=list)),
                ('allowed_intents', models.JSONField(default=list)),
                ('time_window_start', models.TimeField(blank=True, null=True)),
                ('time_window_end', models.TimeField(blank=True, null=True)),
                ('allowed_days', models.JSONField(default=list)),
                ('max_requests_per_hour', models.PositiveIntegerField(blank=True, null=True)),
                ('max_requests_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('emergency_only', models.BooleanField(default=False)),
                ('emergency_escalation', models.BooleanField(default=False)),
                ('forward_to_channels', models.JSONField(default=list)),
                ('auto_response_message', models.TextField(blank=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='gateways.gateway')),
            ],
            options={
                'db_table': 'routing_rules',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('intent', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('action_taken', models.CharField(max_length=50)),
                ('forwarded_to_channels', models.JSONField(default=list)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_logs', to='gateways.gateway')),
                ('routing_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routing.routingrule')),
            ],
            options={
                'db_table': 'routing_logs',
            },
        ),
        migrations.CreateModel(
            name='BlockedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('ip', 'IP Address'), ('phone', 'Phone Number'), ('email', 'Email Address'), ('user_agent', 'User Agent')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_contacts', to='gateways.gateway')),
            ],
            options={
                'db_table': 'blocked_contacts',
                'indexes': [models.Index(fields=['gateway', 'block_type'], name='blocked_con_gateway_ef18eb_idx'), models.Index(fields=['value'], name='blocked_con_value_b34cdf_idx'), models.Index(fields=['expires_at'], name='blocked_con_expires_4722a0_idx')],
                'unique_together': {('gateway', 'block_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Message'), ('offline', 'Offline Message'), ('blocked', 'Blocked Message'), ('rate_limit', 'Rate Limit Message'), ('emergency', 'Emergency Response'), ('auto_reply', 'Auto Reply')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('channels', models.JSONField(default=list)),
                ('intents', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('send_delay_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_templates', to='gateways.gateway')),
            ],
            options={
                'db_table': 'communication_templates',
                'indexes': [models.Index(fields=['gateway', 'template_type', 'is_active'], name='communicati_gateway_6a185a_idx')],
                'unique_together': {('gateway', 'template_type', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='routingrule',
            index=models.Index(fields=['gateway', 'priority', 'is_active'], name='routing_rul_gateway_58c21d_idx'),
        ),
        migrations.AddIndex(
            model_name='routingrule',
            index=models.Index(fields=['emergency_only'], name='routing_rul_emergen_344ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='routinglog',
            index=models.Index(fields=['gateway', 'created_at'], name='routing_log_gateway_0d7aca_idx'),
        ),
        migrations.AddIndex(
            model_name='routinglog',
            index=models.Index(fields=['action_taken'], name='routing_log_action__8b267d_idx'),
        ),
        migrations.AddIndex(
            model_name='routinglog',
            index=models.Index(fields=['success'], name='routing_log_success_9ead6a_idx'),
        ),
    ]
