# Generated by Django 6.0 on 2026-01-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
