# Generated by Django 6.0 on 2026-01-08 19:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_wallet_rechargeorder_wallettransaction_and_more'),
        ('gateways', '0005_pregeneratedqr_direct_service_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('free', 'Free - No Recharge Needed'), ('prepaid', 'Prepaid - Recharge Required'), ('postpaid', 'Postpaid - Bill Later'), ('trial', 'Trial - Limited Free Usage')], default='prepaid', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('free_messages_limit', models.IntegerField(default=0, help_text='Free messages per month')),
                ('free_calls_limit', models.IntegerField(default=0, help_text='Free calls per month')),
                ('message_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('call_cost_per_minute', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(default='💳', max_length=50)),
            ],
            options={
                'verbose_name': 'Recharge Category',
                'verbose_name_plural': 'Recharge Categories',
                'db_table': 'recharge_categories',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RechargePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('message_credits', models.IntegerField(default=0, help_text='Number of messages')),
                ('call_minutes', models.IntegerField(default=0, help_text='Call minutes')),
                ('validity_days', models.IntegerField(default=30, help_text='Plan validity in days')),
                ('bonus_message_credits', models.IntegerField(default=0)),
                ('bonus_call_minutes', models.IntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'verbose_name': 'Recharge Plan',
                'verbose_name_plural': 'Recharge Plans',
                'db_table': 'recharge_plans',
                'ordering': ['display_order', '-amount'],
            },
        ),
        migrations.CreateModel(
            name='QRWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('message_credits', models.IntegerField(default=0)),
                ('call_minutes', models.IntegerField(default=0)),
                ('total_messages_sent', models.IntegerField(default=0)),
                ('total_calls_made', models.IntegerField(default=0)),
                ('total_call_duration', models.IntegerField(default=0, help_text='Total call duration in seconds')),
                ('free_messages_used', models.IntegerField(default=0)),
                ('free_calls_used', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True)),
                ('auto_recharge_enabled', models.BooleanField(default=False)),
                ('auto_recharge_threshold', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('qr_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_wallet', to='gateways.pregeneratedqr')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_wallets', to='accounts.rechargecategory')),
                ('auto_recharge_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_recharge_wallets', to='accounts.rechargeplan')),
            ],
            options={
                'verbose_name': 'QR Wallet',
                'verbose_name_plural': 'QR Wallets',
                'db_table': 'qr_wallets',
            },
        ),
        migrations.CreateModel(
            name='QRWalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('recharge', 'Recharge'), ('deduction', 'Deduction'), ('bonus', 'Bonus'), ('refund', 'Refund'), ('admin_credit', 'Admin Credit'), ('admin_debit', 'Admin Debit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('message_credits', models.IntegerField(default=0)),
                ('call_minutes', models.IntegerField(default=0)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.qrwallet')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.rechargeplan')),
            ],
            options={
                'verbose_name': 'QR Wallet Transaction',
                'verbose_name_plural': 'QR Wallet Transactions',
                'db_table': 'qr_wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
