# Generated by Django 6.0 on 2026-01-09 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rechargecategory_rechargeplan_qrwallet_and_more'),
        ('gateways', '0006_pregeneratedqr_category_qrbatch_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('payment_type', models.CharField(choices=[('message', 'Message'), ('call', 'Call')], default='message', max_length=20)),
                ('visitor_phone', models.CharField(blank=True, max_length=20)),
                ('visitor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message_content', models.TextField(blank=True)),
                ('intent', models.CharField(blank=True, max_length=50)),
                ('channel', models.CharField(blank=True, max_length=20)),
                ('communication_sent', models.BooleanField(default=False)),
                ('communication_sent_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_payments', to='gateways.pregeneratedqr')),
            ],
            options={
                'verbose_name': 'Visitor Payment',
                'verbose_name_plural': 'Visitor Payments',
                'db_table': 'visitor_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
