# Generated by Django 6.0 on 2026-01-22 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_visitorpayment'),
        ('gateways', '0007_qrbatch_delivered_at_qrbatch_print_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargecategory',
            name='distributor_activation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='One-time payment for distributor category activation', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rechargecategory',
            name='category_type',
            field=models.CharField(choices=[('free', 'Free - No Recharge Needed'), ('prepaid', 'Prepaid - Recharge Required'), ('postpaid', 'Postpaid - Bill Later'), ('trial', 'Trial - Limited Free Usage'), ('distributor', 'Distributor - One-Time Payment')], default='prepaid', max_length=20),
        ),
        migrations.CreateModel(
            name='DistributorPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_payment', to='gateways.pregeneratedqr')),
            ],
            options={
                'verbose_name': 'Distributor Payment',
                'verbose_name_plural': 'Distributor Payments',
                'db_table': 'distributor_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
