# Generated by Django 6.0 on 2026-01-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rechargecategory_distributor_activation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distributor_registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='distributor_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_distributor',
            field=models.BooleanField(default=False),
        ),
    ]
