# Generated by Django 6.0 on 2026-01-23 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_distributor_registered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorpayment',
            name='distributor',
            field=models.ForeignKey(blank=True, help_text='Distributor who provided this QR code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
