# Generated by Django 6.0 on 2026-01-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_distributorpayment_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distributor_commission_per_activation',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission earned per QR activation', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='distributor_total_qr',
            field=models.PositiveIntegerField(default=0, help_text='Total QR codes assigned by admin'),
        ),
    ]
