# Generated by Django 6.0 on 2026-01-03 18:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_token', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(max_length=20)),
                ('intent', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('response_sent', models.BooleanField(default=False)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_sessions', to='gateways.gateway')),
            ],
            options={
                'db_table': 'interaction_sessions',
            },
        ),
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel_used', models.CharField(max_length=20)),
                ('intent', models.CharField(max_length=20)),
                ('message_content', models.TextField()),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('was_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('response_sent', models.BooleanField(default=False)),
                ('response_channel', models.CharField(blank=True, max_length=20)),
                ('response_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='gateways.gateway')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='interactions.interactionsession')),
            ],
            options={
                'db_table': 'interaction_logs',
            },
        ),
        migrations.CreateModel(
            name='InteractionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_interactions', models.PositiveIntegerField(default=0)),
                ('successful_interactions', models.PositiveIntegerField(default=0)),
                ('blocked_interactions', models.PositiveIntegerField(default=0)),
                ('failed_interactions', models.PositiveIntegerField(default=0)),
                ('sms_interactions', models.PositiveIntegerField(default=0)),
                ('whatsapp_interactions', models.PositiveIntegerField(default=0)),
                ('ivr_interactions', models.PositiveIntegerField(default=0)),
                ('email_interactions', models.PositiveIntegerField(default=0)),
                ('general_interactions', models.PositiveIntegerField(default=0)),
                ('emergency_interactions', models.PositiveIntegerField(default=0)),
                ('complaint_interactions', models.PositiveIntegerField(default=0)),
                ('business_interactions', models.PositiveIntegerField(default=0)),
                ('avg_response_time_seconds', models.FloatField(blank=True, null=True)),
                ('peak_hour', models.PositiveIntegerField(blank=True, null=True)),
                ('top_countries', models.JSONField(default=dict)),
                ('top_cities', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_analytics', to='gateways.gateway')),
            ],
            options={
                'db_table': 'interaction_analytics',
                'indexes': [models.Index(fields=['gateway', 'date'], name='interaction_gateway_0c8311_idx'), models.Index(fields=['date'], name='interaction_date_43ae54_idx')],
                'unique_together': {('gateway', 'date')},
            },
        ),
        migrations.CreateModel(
            name='InteractionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate'), ('helpful', 'Helpful'), ('resolved', 'Issue Resolved'), ('escalate', 'Needs Escalation')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('blocked_contact', models.BooleanField(default=False)),
                ('forwarded_to_support', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interaction_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='interactions.interactionlog')),
            ],
            options={
                'db_table': 'interaction_feedback',
                'indexes': [models.Index(fields=['feedback_type'], name='interaction_feedbac_6823df_idx'), models.Index(fields=['created_at'], name='interaction_created_d53c67_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunicationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('message_content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('provider_name', models.CharField(blank=True, max_length=50)),
                ('provider_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_attempts', to='interactions.interactionlog')),
            ],
            options={
                'db_table': 'communication_attempts',
                'indexes': [models.Index(fields=['interaction_log', 'status'], name='communicati_interac_4dcc9c_idx'), models.Index(fields=['channel'], name='communicati_channel_f1141d_idx'), models.Index(fields=['status'], name='communicati_status_470bc1_idx'), models.Index(fields=['external_id'], name='communicati_externa_995809_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='interactionsession',
            index=models.Index(fields=['session_token'], name='interaction_session_4b2ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionsession',
            index=models.Index(fields=['gateway', 'status'], name='interaction_gateway_417c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionsession',
            index=models.Index(fields=['expires_at'], name='interaction_expires_3ddb3c_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionsession',
            index=models.Index(fields=['ip_address'], name='interaction_ip_addr_6e277e_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['gateway', 'initiated_at'], name='interaction_gateway_905eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['channel_used'], name='interaction_channel_1b7434_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['intent'], name='interaction_intent_428458_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['was_blocked'], name='interaction_was_blo_6b5f95_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['success'], name='interaction_success_e3e71a_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['ip_address'], name='interaction_ip_addr_6fb163_idx'),
        ),
    ]
