# Generated by Django 6.0 on 2026-01-03 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('twilio_sms', 'Twilio SMS'), ('twilio_voice', 'Twilio Voice'), ('whatsapp_business', 'WhatsApp Business API'), ('django_email', 'Django Email Backend'), ('custom', 'Custom Provider')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.JSONField(default=dict)),
                ('daily_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=10)),
                ('daily_usage', models.PositiveIntegerField(default=0)),
                ('monthly_usage', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communication_providers',
                'unique_together': {('name', 'provider_type')},
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('message_content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cost_currency', models.CharField(default='USD', max_length=3)),
                ('provider_response', models.JSONField(default=dict)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.communicationprovider')),
            ],
            options={
                'db_table': 'communication_logs',
                'indexes': [models.Index(fields=['channel', 'status'], name='communicati_channel_18f14b_idx'), models.Index(fields=['created_at'], name='communicati_created_b71929_idx'), models.Index(fields=['external_id'], name='communicati_externa_8228cb_idx')],
            },
        ),
    ]
