# Generated by Django 6.0 on 2026-01-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pricingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagorder',
            name='distributor_code',
            field=models.CharField(blank=True, db_index=True, help_text="Distributor's mobile number", max_length=15),
        ),
    ]
