# Generated by Django 6.0 on 2026-01-03 18:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('context_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('home', 'Home/Property'), ('office', 'Office/Business'), ('asset', 'Asset/Equipment'), ('person', 'Personal'), ('service', 'Service'), ('other', 'Other')], max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('identifier_text', models.CharField(blank=True, max_length=100)),
                ('is_emergency_enabled', models.BooleanField(default=True)),
                ('auto_response_enabled', models.BooleanField(default=False)),
                ('auto_response_message', models.TextField(blank=True)),
                ('total_interactions', models.PositiveIntegerField(default=0)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gateways',
            },
        ),
        migrations.CreateModel(
            name='EntryPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('qr', 'QR Code'), ('shortlink', 'Short Link'), ('ivr', 'IVR Number'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('public_identifier', models.CharField(max_length=100, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_points', to='gateways.gateway')),
            ],
            options={
                'db_table': 'entry_points',
            },
        ),
        migrations.CreateModel(
            name='GatewayAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_interactions', models.PositiveIntegerField(default=0)),
                ('successful_interactions', models.PositiveIntegerField(default=0)),
                ('blocked_interactions', models.PositiveIntegerField(default=0)),
                ('sms_interactions', models.PositiveIntegerField(default=0)),
                ('whatsapp_interactions', models.PositiveIntegerField(default=0)),
                ('ivr_interactions', models.PositiveIntegerField(default=0)),
                ('qr_accesses', models.PositiveIntegerField(default=0)),
                ('shortlink_accesses', models.PositiveIntegerField(default=0)),
                ('top_countries', models.JSONField(default=dict)),
                ('top_cities', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='gateways.gateway')),
            ],
            options={
                'db_table': 'gateway_analytics',
            },
        ),
        migrations.CreateModel(
            name='GatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_channels', models.JSONField(default=list)),
                ('blocked_channels', models.JSONField(default=list)),
                ('available_start_time', models.TimeField(blank=True, null=True)),
                ('available_end_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('max_interactions_per_hour', models.PositiveIntegerField(default=10)),
                ('max_interactions_per_day', models.PositiveIntegerField(default=50)),
                ('welcome_message', models.TextField(blank=True)),
                ('offline_message', models.TextField(blank=True)),
                ('log_interactions', models.BooleanField(default=True)),
                ('store_contact_info', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='gateways.gateway')),
            ],
            options={
                'db_table': 'gateway_settings',
            },
        ),
        migrations.AddIndex(
            model_name='gateway',
            index=models.Index(fields=['owner', 'is_active'], name='gateways_owner_i_25a6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='gateway',
            index=models.Index(fields=['context_type'], name='gateways_context_59d55e_idx'),
        ),
        migrations.AddIndex(
            model_name='gateway',
            index=models.Index(fields=['created_at'], name='gateways_created_ec9123_idx'),
        ),
        migrations.AddIndex(
            model_name='entrypoint',
            index=models.Index(fields=['public_identifier'], name='entry_point_public__6a7f88_idx'),
        ),
        migrations.AddIndex(
            model_name='entrypoint',
            index=models.Index(fields=['gateway', 'is_active'], name='entry_point_gateway_82660c_idx'),
        ),
        migrations.AddIndex(
            model_name='entrypoint',
            index=models.Index(fields=['type'], name='entry_point_type_ba5fce_idx'),
        ),
        migrations.AddIndex(
            model_name='gatewayanalytics',
            index=models.Index(fields=['gateway', 'date'], name='gateway_ana_gateway_6225f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gatewayanalytics',
            unique_together={('gateway', 'date')},
        ),
    ]
