# Generated by Django 6.0 on 2026-01-05 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrypoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='QRBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('activated_count', models.PositiveIntegerField(default=0)),
                ('reserved_count', models.PositiveIntegerField(default=0)),
                ('available_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qr_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'QR Batches',
                'db_table': 'qr_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreGeneratedQR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/pregenerated/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('activated', 'Activated'), ('expired', 'Expired'), ('disabled', 'Disabled')], db_index=True, default='available', max_length=20)),
                ('activation_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by_admin', models.BooleanField(default=False)),
                ('batch_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_code', to='gateways.gateway')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pregenerated_qr_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['qr_code'], name='pregenerate_qr_code_391ac8_idx'), models.Index(fields=['status', 'created_at'], name='pregenerate_status_4cdabd_idx'), models.Index(fields=['owner', 'status'], name='pregenerate_owner_i_1ddab4_idx'), models.Index(fields=['batch_number'], name='pregenerate_batch_n_b2ee97_idx')],
            },
        ),
    ]
