# Generated by Django 6.0 on 2026-01-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0002_alter_entrypoint_created_at_alter_gateway_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
