# Generated by Django 6.0 on 2026-01-05 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0003_gateway_owner_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gateway',
            index=models.Index(fields=['identifier_text', 'is_active'], name='gateways_identif_b05326_idx'),
        ),
    ]
