# Generated by Django 6.0 on 2026-01-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0004_gateway_gateways_identif_b05326_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregeneratedqr',
            name='direct_service_enabled',
            field=models.BooleanField(default=True, help_text='Enable free direct service for this QR'),
        ),
        migrations.AddField(
            model_name='pregeneratedqr',
            name='service_mode',
            field=models.CharField(choices=[('direct', 'Direct Service (Free)'), ('wallet', 'Wallet Service (Paid)'), ('both', 'Both Services')], default='direct', help_text='Admin decides if this QR uses wallet service, direct service, or both', max_length=20),
        ),
        migrations.AddField(
            model_name='pregeneratedqr',
            name='wallet_enabled',
            field=models.BooleanField(default=False, help_text='Enable wallet-based paid calls for this QR'),
        ),
    ]
