# Generated by Django 6.0 on 2026-01-09 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rechargecategory_rechargeplan_qrwallet_and_more'),
        ('gateways', '0005_pregeneratedqr_direct_service_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregeneratedqr',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category determines pricing and features', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='accounts.rechargecategory'),
        ),
        migrations.AddField(
            model_name='qrbatch',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for all QR codes in this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_batches', to='accounts.rechargecategory'),
        ),
    ]
