# Generated by Django 6.0 on 2026-01-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0006_pregeneratedqr_category_qrbatch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrbatch',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrbatch',
            name='print_notes',
            field=models.TextField(blank=True, help_text='Notes about printing process'),
        ),
        migrations.AddField(
            model_name='qrbatch',
            name='print_status',
            field=models.CharField(choices=[('generated', 'Generated'), ('sent_for_print', 'Sent for Print'), ('printing', 'Printing'), ('printed', 'Printed'), ('delivered', 'Delivered')], default='generated', help_text='Current status of batch printing', max_length=20),
        ),
        migrations.AddField(
            model_name='qrbatch',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrbatch',
            name='printing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrbatch',
            name='sent_for_print_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
