# Generated by Django 6.0 on 2026-01-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0007_qrbatch_delivered_at_qrbatch_print_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='distributor_code',
            field=models.CharField(blank=True, help_text='Distributor mobile number used during activation', max_length=20),
        ),
    ]
